version: "3.9"

services:
  db:
    image: postgres:14.3
    ports:
      - "30310:5432"
    volumes:
      - db-var_lib_postgresql_data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
      - PGTZ=Asia/Seoul
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=restaurant

volumes:
  db-var_lib_postgresql_data: